from typing import Tuple
from PIL import Image
import numpy as np
import torch

# Each DINOv2 patch is 14x14
PATCH_DIM = 14

# - 1 for dinov2
# - 1 + 4 for dinov2-with-registers
DINOV2_EMBEDDINGS_OFFSET = 1
DINOV2_WITH_REG_EMBEDDINGS_OFFSET = 1 + 4


def _into_tensor(image: Image.Image, mode: str, device: str) -> torch.Tensor:
    # Only breaks with this mode
    if image.mode == "I;16":
        return _into_tensor(
            image.point(lambda p: p / 256.0).convert("RGB"), mode, device
        )

    # Resample; these images can't be processed efficiently in their native size,
    # and the resolution is so high that it will barely make any difference in the output
    if image.width * image.height >= 16384 * 16384:
        image = image.resize(image.width // 2, image.height // 2)

    return (
        torch.from_numpy(np.array(image.convert(mode), dtype=np.float32))
        .to(device)
        .div(255.0)
        .permute((2, 0, 1))
    )


def _strip_transparency(image: Image.Image, device: str) -> torch.Tensor:
    w = image.width
    h = image.height

    if not image.has_transparency_data:
        return _into_tensor(image, "RGB", device)

    pixels = _into_tensor(image, "RGBA", device)

    # Get channels
    alpha = pixels[3, :, :].expand((3, h, w))
    color = pixels[:3, :, :]

    # Detect whether premultiplication should be applied by checking
    # for channels with values above the alpha level.
    #
    # Note that the only input format which we can get where this would
    # be relevant, PNG, explicitly says it does not carry premultiplied alpha,
    # but many tools will store premultiplied alpha anyway...
    ones = torch.ones((3, h, w), dtype=torch.float32, device=device)
    mask = torch.where(color.gt(alpha).any(), alpha, ones)
    color = color.mul(mask)

    # Pure transparency is rescaled to be 8 steps "blacker than black."
    alpha_level = 8.0 / 255.0
    color_level = 1 - alpha_level

    return color.multiply(color_level).add(alpha.multiply(alpha_level))


def _resize_tensor(image: torch.Tensor, size: Tuple[int, int]) -> torch.Tensor:
    return torch.nn.functional.interpolate(
        image, size=size, mode="bicubic", align_corners=True
    )


def _load_image(path: str, device: str) -> torch.Tensor:
    image = Image.open(path)
    image = _strip_transparency(image, device)
    return image


def _infer(image: torch.Tensor, model: torch.ScriptModule):
    return model(image)


def _scaled_result(pooler_output: torch.Tensor) -> torch.Tensor:
    scaled_norm = pooler_output.norm().pow(-1)
    return pooler_output.multiply(scaled_norm)


def _resize_image_by_patch_count(
    image: torch.Tensor, size: Tuple[int, int]
) -> torch.Tensor:
    # Compute effective side lengths of the rescaled image.
    height = size[0] * PATCH_DIM
    width = size[1] * PATCH_DIM

    return _resize_tensor(image.unsqueeze(0), (height, width))


def get_model_result(path: str, model: torch.ScriptModule, device: str) -> torch.Tensor:
    """
    Get the feature vector corresponding to the given image path, on the given device,
    using the given model.
    """

    # Get image and dimensions for calculation.
    image = _load_image(path, device)

    # Features are unstable across different global scales, and
    # somewhat stable across dimensional scales.
    #
    # Use 18 (252x252) instead of 16 (224x224) to produce a more detailed
    # result and attention map at almost exactly the same computational cost.
    #
    # It is possible for highly non-square models to have meaningful feature extraction,
    # but in practice it makes no difference identifying scales which keep the aspect
    # ratio, and does not produce feature vectors which are similar enough to identify
    # crops.
    image_scale = 1
    height_patches, width_patches = (18 * image_scale, 18 * image_scale)

    # Load and scale image into appropriate shape
    image = _resize_image_by_patch_count(image, (height_patches, width_patches))

    # The pooler output is the [CLS] token generated by the model.
    # It contains high-quality, robust features from the input image.
    _last_hidden_state, pooler_output = _infer(image, model)

    return _scaled_result(pooler_output.squeeze())
